branch-defaults:
  master:
    environment: staging
  production:
    environment: production
global:
  application_name: falco-new
  default_region: eu-west-2
  sc: git
  workspace_type: Application
deploy:
  artifact: archive.zip
